name: Template CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        with:
            project-dir: .
        
    format:
        uses: ./.github/workflows/format.yml
        with:
            project-dir: .

    type-check:
        uses: ./.github/workflows/type-check.yml
        with:
            project-dir: .
    test:
        uses: ./.github/workflows/test.yml
        with:
            project-dir: .