name: Check format using Ruff

on:
    workflow_call:
        inputs:
            project-directory:
                type: string
                required: true

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check format using Ruff
              uses: chartboost/ruff-action@v1
              with:
                src: ${{ github.event.inputs.project-directory }}
                args: 'format --check'
