name: Test using Pytest

on: 
    workflow_call:
        inputs:
            project-directory:
                type: string
                required: true

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5.1.0
              with:
                  python-version: '3.10'
            - name: Install dependencies
              working-directory: ${{ inputs.project-directory }}
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install
            - name: Test with pytest
              working-directory: ${{ inputs.project-directory }}
              run: poetry run pytest -rA -x --color=yes