name: Type check using Mypy

on:
    workflow_call:
        inputs:
            project-directory:
                type: string
                required: true

jobs:
    mypy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v5.1.0
              with:
                python-version: '3.10'
            - name: Install dependencies
              working-directory: ${{ inputs.project-directory }}
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install
            - name: Type check with mypy
              working-directory: ${{ inputs.project-directory }}
              run: poetry run mypy .